website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = '3930190'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    
    db.init_app(app) 
    
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Note
    
    create_database(app)
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database(app):
    if not path.exists("website/" + DB_NAME):
        with app.app_context():
            db.create_all()
        print("Database created")

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, logout_user, login_required, current_user

auth = Blueprint('auth', __name__)

BANLIST = []


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get("password")
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                if current_user.id in BANLIST:
                    logout_user()
                    flash('You are banned from FlashForum!', category='error')
                    return redirect(url_for('auth.login'))
                flash('Logged in!', category='success')
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password!', category="error")
        else:
            flash("Account does not exist!", category='error')
        
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == "POST":
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email is already registered!', category='error')
        elif len(email) < 4:
            flash("Email is too short!", category='error')
        elif password1 != password2:
            flash("Passwords don't match!", category='error')
        elif len(password1) < 7:
            flash("Password is too short!", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash("Account created!", category='success')
            return redirect(url_for('views.home'))
    
    return render_template("sign_up.html", user=current_user)

@auth.route('/banned', methods=["GET", "POST"])
def banned():
    return render_template("banned.html", user=current_user)

@auth.route('/ban-user/<user_id>', methods=['POST'])
def ban_user(user_id):
    user = User.query.get(user_id)
    if user:
    
        user.banned = True
        db.session.commit()
    
    return redirect(url_for('views.home'))

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Note
from .auth import BANLIST
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, logout_user, login_required, current_user

admins = [1]

auth = Blueprint('auth', __name__)
views = Blueprint('views', __name__)

@views.route('/', methods=["GET", "POST"])
@login_required
def home():
    if current_user.id in BANLIST:
        logout_user()
        flash('You are banned from FlashForum!', category='error')
        return redirect(url_for('auth.banned'))
    
    if request.method == "POST":
        note = request.form.get('note')

        if len(note) < 1:
            flash("Your post is too short!", category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Posted!', category="success")

    notes = Note.query.all()
    return render_template("home.html", user=current_user, notes=notes, admins=admins)

@views.route('/remove-note/<int:note_id>', methods=['POST'])
@login_required
def remove_note(note_id):
    note = Note.query.get_or_404(note_id)

    if note.user_id == current_user.id:
        db.session.delete(note)
        db.session.commit()
        flash('Your post was removed successfully!', category='success')
    elif current_user.id in admins:
        db.session.delete(note)
        db.session.commit()
        flash('Admin-removed successfully!', category='error')
    else:
        flash('This is not your post!', category='error')

    return redirect(url_for('views.home'))

@views.route('/admin', methods=["GET", "POST"])
@login_required
def admin():
    ban_string = ""
    
    if request.method == "POST":
        user_id = request.form.get('user_id')
        flash("Variable " + user_id + " has been created!", category='success')
        
    
    return render_template("admin.html", user=current_user, ban_value=ban_string, admins=admins)



website/templates/admin.html
{% extends "base.html" %}

{% block title %}
    FlashForum Admin Panel
{% endblock %}

{% block content %}
{% if current_user.id in admins %}
<h1 align="center" style="color: red">Admin panel</h1>
<h2 align="center" style="color: gray">Admin ID: #{{ current_user.id }}</h2>

<form method="POST" action="{{ url_for('views.admin') }}">
</br>
    <textarea name="user_id" id="user_id" class="form-control" placeholder="Create variable"></textarea>
    </br>
    <div align="center">
        <button type="submit" class="btn btn-danger btn-sm">Variable</button>
    </div>
</form>

{% endif %}

{% if not current_user.id in admins %}
<h1 style="color: red" align="center">You don't have access to the admin panel!</h1>
<center><a href="/" class="btn btn-primary">Go back</a></center>
{% endif %}
{% endblock %}

website/templates/banned.html
{% extends "base.html" %}

{% block title %}
    You are banned from FlashForum!
{% endblock %}

{% block content %}
    <h1 style="color: red" align="center">You are banned!</h1>
    <h2>You are banned from FlashForum for unknown reasons!</br></h2>
<h3>Recent reasons of ban:</br>
- Racist activity</br>
- Swearing</br>
- Posting content about war on Ukraine</h3>

<form method="POST">
        <textarea name="appeal" id="appeal" class="form-control"></textarea>
        <br />
        <div align="center">
            <button type="submit" class="btn btn-primary">Appeal</button>
        </div>
    </form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <mtea name="viewport" content="width=device-width", initial-scale=1 />
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
        />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
        />

        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navabr-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
           {% for category, message in messages %}
           {% if category == 'error' %}
           <div class="alert alert-danger alert-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
           </div>
           {% else %}
           <div class="alert alert-success alert-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
           </div>
           {% endif %}
           {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
       ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>

        <script type="text/javascript" src"{{ url_for('static', filename="index.js") }}
        ></script>
    </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}
    FlashForum HomePage
{% endblock %}

{% block content %}
    <h1 align="center">What's new today?</h1>
    <h2 style='color: gray' align="center">Account ID: #{{ current_user.id }}</h2>
    {% if current_user.id in admins %}
        <h2 style="color: red" align="center">Admin rights</h2>
        <a href="/admin" class="btn btn-secondary" style="position: absolute; top: 10px; right: 10px;">Admin Panel</a>
    {% endif %}

    <ul class="list-group list-group-flush" id="notes">
        {% for note in notes %}
            <li class="list-group-item">
                {{ note.data }}
                <form action="{{ url_for('views.remove_note', note_id=note.id) }}" method="POST" class="d-inline">
                    {% if current_user.id == note.user_id %}
                        <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                    {% endif %}
                    {% if current_user.id in admins %}
                        {% if current_user.id != note.user_id %}
                            <button type="submit" class="btn btn-secondary">Admin-Remove</button>
                        {% endif %}
                    {% endif %}
                    </br>
                    <h7 style="color: gray">Posted by #{{ note.user_id }}</h7>
                </form>
            </li>
        {% endfor %}
    </ul>

    <form method="POST">
        <textarea name="note" id="note" class="form-control"></textarea>
        <br />
        <div align="center">
            <button type="submit" class="btn btn-primary">Flash-Post!</button>
        </div>
    </form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}FlashForum Login{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login to FlashForum</h3>
    <div class="from-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="example@email.com"/>
    </div>
    </br>
    <div class="from-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="MyPassword123"/>
    </div>
    <br />

    <center><button type="submit" class="btn btn-primary">Login to account</button></center>
    </br>
    <center><a href="/sign-up" class="btn btn-secondary">I don't have account yet</a></center>


</form>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}FlashForum Sign Up{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Sign-Up to FlashForum</h3>
    <div class="from-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="example@email.com"/>
    </div>
    </br>
    <div class="from-group">
        <label for="firstName">Username</label>
        <input type="text" class="form-control" id="firstName" name="firstname" placeholder="SomeSuperUsername"/>
    </div>
    </br>
    <div class="from-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="SuperSecretPassword123"/>
    </div>
    </br>
    <div class="from-group">
        <label for="password2">Repeat password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="SuperSecretPassword123"/>
    </div>
    <br />

    <center><button type="submit" class="btn btn-primary">Create account</button></center>
    </br>
    <center><a href="/login" class="btn btn-secondary">Login to existing account</a></center>

</form>
{% endblock %}